export * from './icons/index'
export * from './icons/home'
export * from './icons/dashboard'

export * from './layouts/AppBar'
// export * from './layouts/AppBar2'
// export * from './layouts/Actionsfooter'
export * from './layouts/footer'
export * from './layouts/config'
export * from './layouts/dashboard/tooggleMenu'
export * from './layouts/dashboard/DropMenu'
export * from './layouts/dashboard/aside'

export * from './auth/_login'
export * from './auth/_create'
export * from './auth/socialAuth'

export * from './home/Index'
export * from './home/settings/_topHome'
export * from './home/settings/_keyFeatures'
export * from './home/settings/_cadastro'
export * from './home/create/create'
export * from './home/carouselImage'

export * from './forms/profile/profile'
export * from './forms/profile/address'
export * from './forms/profile/formBio'
export * from './forms/profile/ocopacoes/RegisterOcupacao'

export * from './forms/user/userData'
export * from './forms/formDialog'

export * from './listas/listadepaises'
export * from './listas/listaDeItens'
export * from './listas/listaDeOcupacoes'
export * from './listas/cargos'

export * from './user/listadeCasas'
export * from './user/homeDashboard'
export * from './user/tabDashboard'