export const listaDeOcupacoes = [
  'Estudante',
  'Trabalhador',
  'Engenheiro',
  'Médico',
  'Professor',
  'Advogado',
  'Arquiteto',
  'Enfermeiro',
  'Cientista',
  'Artista',
  'Músico',
  'Escritor',
  'Design Gráfico',
  'Programador',
  'Psicólogo',
  'Chef de Cozinha',
  'Contador',
  'Jornalista',
  'Fotógrafo',
  'Atleta',
  'Militar',
  'Policial',
  'Trabalhador Social',
  'Veterinário',
  'Empreendedor',
  'Biólogo',
  'Economista',
  'Técnico de Informática',
  'Piloto',
  'Cabeleireiro',
  'Esteticista',
  'Bibliotecário',
  'Turismólogo',
  'Analista de Sistemas',
  'Gestor de Projetos',
  'Agricultor',
  'Eletricista',
  'Mecânico',
  'Cineasta',
  'Tradutor',
]