export * from './hero'
export * from './aside'
export * from './footer2'
export * from './services'
export * from './portfolioSection'
export * from './ContactFormSection'
export * from './diferenciaisSection'
export * from './testimonialsSection'